### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by al-prater-deltatre** [AppsFlyerSDK/appsflyer-adobe-mobile-ios-extension#18]
Given that the latest [AppsFlyerFramework](https://github.com/AppsFlyerSDK/AppsFlyerFramework) (6.1.0+) only supports SPM, can this extension also be updated for SPM too please?
Many thanks

**Comment by pazlavi** [comment]
Available for the new Swift extension https://github.com/AppsFlyerSDK/appsflyer-adobe-mobile-ios-swift-extension
