### ISSUE TITLE
Arm64 Compatibility

### ISSUE THREAD

**Issue by digitalbrain** [AppsFlyerSDK/appsflyer-adobe-mobile-ios-extension#26]
Currently AppsFlyerAdobeExtension seems to be not supported iOs simulator on new m1 mac, due to pod dependency  ​
​AppsFlyerFramework (= 6.2.6)

The dependecy should be uptated to 6.3.0

**Comment by pazlavi** [comment]
Hi @digitalbrain 
Thank you for reaching out to us.

An `AppsFlyerAdobeExtension`  update will probably be released by the end of the next week.

**Comment by digitalbrain** [comment]
@pazlavi  thank you

**Comment by tadija** [comment]
did you forget to `pod trunk push` for the latest 6.3.1 release?
