### ISSUE TITLE
Add support for new Adobe Swift SDKs

### ISSUE THREAD

**Issue by tadija** [AppsFlyerSDK/appsflyer-adobe-mobile-ios-extension#29]
New Adobe Swift SDKs (AEP*) support SPM and M1 arch but this extension is still depending on the old Adobe SDKs (ACP*), thus preventing us from upgrading to the new Adobe Swift SDKs:

https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/current-sdk-versions

**Comment by Gopinatha-L** [comment]
+1

**Comment by pazlavi** [comment]
https://github.com/AppsFlyerSDK/appsflyer-adobe-mobile-ios-swift-extension
